services:
  db_wallet:
      container_name: db_wallet
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      image: postgres:15-alpine
      ports:
        - ${POSTGRES_PORT}:${POSTGRES_PORT}
      command:
        - 'postgres'
        - '-c'
        - 'port=${POSTGRES_PORT}'
      volumes:
        - db_wallet_vol:/var/lib/postgresql/data
      networks:
        - server_net
  api_wallet:
    container_name: api_wallet
    build: ./api
    depends_on:
      - db_wallet
    networks:
      - server_net
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      API_PORT: ${API_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_NAME: ${POSTGRES_NAME}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USE_SSL: ${POSTGRES_USE_SSL}

volumes: 
  db_wallet_vol: {}

networks:
  server_net:
    driver: bridge


# docker compose --env-file config.env up --build -d



